apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Synced to the cluster by Argo CD (see ../argocd-application.yaml)
resources:
- configmap.yaml
- deployment.yaml
- gateway.yaml
- route.yaml
# The release workflow sets the image to the one built from the latest commit
images:
- name: parthvasave/log-output
  newName: asia-south1-docker.pkg.dev/devops-kubernetes-508609/exercises/log-output
  newTag: 03781f7b92162326db7709dff6236320260f3ef0
