apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: exercises
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:haItxnDrn3o=,iv:upMeVOfbtfp6sHYSlgThSJkERiKin+j0Vda3WeqnGHk=,tag:RDFR/Y5t0MhvncH8VXxiFA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qkUEWRVb8DA=,iv:GE+UuPlPhOK1ik3RYljI1V4UfGFuI3XmFAMJGGv3m+k=,tag:gY6HVwReJtp8mEhFUbgVlg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:k90LObSHC5JjrsPW46Y5DkOfERo78pBqR2iFuc3znAk=,iv:waZuDEwUjOfb/OoRZqdDuuvpBe5FCDKZa3RFd/n63jI=,tag:RfbvRHL+9t2o5Cb2h6xVYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRUxXL1FnNFFMSDJmQ0lL
            TTNuSkpGZ0Y2emRLVDhJY0RTdGRrNitEem5rCmZsMm12WUJQZVBVR0tzRkxGcGJt
            SGFMUHYxSW05MGVwOEZuRUtrQzJZbTQKLS0tIGlIVmwzYkJOK24rdDhSQjZNY2Z1
            U0R6cGUveVZIc1EwNk1MakEzVnl5L0EKkko7sMPYh2J+PVHLDo5gQAuMrpdLA2MY
            aTq98KJ5WhE1WE6AgTF1NxaOyyI9cw//DNB6f8CK2tl4/0pNJC1SEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15fad92qkqrfwuwrp6j68z9jeteg9ht9r0zlqk8fzw4yq6lwee3zshrcvgf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T08:53:46Z"
    mac: ENC[AES256_GCM,data:vH1EAszHH8jwFjuM1Cd4vTqeLNR6p0/DazT7zjPmU3fOWEoqi1IRyJ+GJxmavdKMGtgWUmdn7QCqVC2RefkVyPXXGNKOFdtwhouzU076WA+67g12YdI6XDTTvInsLyKVGYNev2u766n2x3/LVTModP7ibYI4l8nCcFR1XzWZ07w=,iv:8YQHdQaPkAUNdojZcMTQ4S4YqfM2NhkKlTxfDNjj6uI=,tag:TuD5rCTq+ELYqVMDMsDGog==,type:str]
    version: 3.13.3
