apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
spec:
  storageClassName: manual-todo
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/todo-data"
