apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
  namespace: project
spec:
  storageClassName: manual-todo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
